FROM ghcr.io/akdev1l/container-images/base:latest

RUN dnf5 install -y \
    iotop

ENTRYPOINT ["iotop"]
LABEL RUNCMD /usr/bin/podman run --rm -it --security-opt label=disable --pid=host --privileged \${IMAGE}
