FROM ghcr.io/akdev1l/container-images/base:latest

RUN dnf5 install -y \
        @development-tools \
        'gcc-c++' \
        'libstdc++-devel' \
        git \
        make \
        rubygems \
        ruby-devel \
        rubygem-eventmachine \
        rubygem-jekyll \
        rubygem-racc \
        rubygem-unf \
        rubygem-unf_ext && \
    bundle config set --local path 'vendor/bundle'
    

ENTRYPOINT ["jekyll"]
