FROM ghcr.io/ublue-os/kinoite-nvidia:latest

RUN dnf install -y \
    rclone \
    virt-manager \
    zsh \
    NetworkManager-ovs \
    openvswitch \
    ;

# Install cosign public key and enforce signature verification for akdev1l images
RUN mkdir -p /usr/etc/pki/containers
COPY akdev.pub /usr/etc/pki/containers/akdev.pub
COPY policy.json /usr/etc/containers/policy.json
