FROM ghcr.io/akdev1l/kinoite-nvidia:44

RUN dnf install -y \
    rclone \
    virt-manager \
    zsh \
    NetworkManager-ovs \
    openvswitch \
    openrgb-udev-rules \
    ;

# Install cosign public key and enforce signature verification for akdev1l images
RUN mkdir -p /usr/etc/pki/containers
COPY akdev.pub /usr/etc/pki/containers/akdev.pub
COPY policy.json /usr/etc/containers/policy.json
COPY akdev.yaml /usr/etc/containers/registries.d/akdev.yaml
