FROM fedora:latest
ARG KERNEL_REPO=https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux
ARG KERNEL_NEXT_REPO=https://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next
ARG KERNEL_SRC_DIR=/usr/src/kernel
ARG KERNEL_OUT_DIR=/var/lib/kernel

VOLUME ${KERNEL_OUT_DIR}

RUN dnf install -y flex bison gcc make git \
                   openssl-devel elfutils-libelf-devel bc \
                   findutils && \
    git clone --branch master --depth 1 ${KERNEL_REPO} ${KERNEL_SRC_DIR}

WORKDIR ${KERNEL_SRC_DIR}

RUN git remote add linux-next ${KERNEL_NEXT_REPO}

COPY config .config
COPY build-kernel /usr/local/bin/build-kernel

ENTRYPOINT ["/usr/local/bin/build-kernel"]
