#!/bin/bash

NORD_VPN_CONFIG_ZIP=https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
OPENVPN_CONFIG_DIR=/etc/openvpn/client

dnf upgrade -y
dnf install -y unzip findutils

/usr/local/bin/nordvpn.sh
