#!/bin/bash

NORD_VPN_CONFIG_ZIP=https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
OPENVPN_CONFIG_DIR=/etc/openvpn/client

dnf upgrade -y
dnf install -y unzip findutils

/usr/local/bin/nordvpn.sh

# Post build

OPENVPN_CONFIG_DIR=${OPENVPN_CONFIG_DIR:-/etc/openvpn/client}
OPENVPN_PROFILE=${OPENVPN_PROFILE:-ca1100.nordvpn.com.udp}

dnf install -y openvpn
COPY --from=0 /tmp/ovpn ${OPENVPN_CONFIG_DIR}

ADD entrypoint.sh /entrypoint.sh
ADD health-check /usr/local/bin/health-check

HEALTHCHECK CMD /health.sh

ENTRYPOINT ["/entrypoint.sh"]
