FROM fedora:latest
LABEL RUN="podman run \
    --rm \
    --security-opt label=disable \
    -it \
    -v \$PWD:\$PWD \
    -w \$PWD \
    \$IMAGE '$@'"

RUN dnf install -y \
    ripgrep

ENTRYPOINT ["rg"]
