FROM ghcr.io/akdev1l/container-images/base:latest
LABEL xyz.akdev.run="podman run \
    --rm \
    --security-opt label=disable \
    -it \
    -v \$PWD:\$PWD \
    -w \$PWD \
    \$IMAGE '$@'"

RUN dnf5 install -y \
    ripgrep

ENTRYPOINT ["rg"]
