FROM fedora:latest

RUN dnf install -y \
    ripgrep

ENTRYPOINT ["rg"]

LABEL runcmd podman run \
    --rm \
    --security-opt label=disable \
    -it \
    -v \$PWD:\$PWD \
    -w \$PWD \
    \$IMAGE "$@"
