FROM ghcr.io/akdev1l/container-images/base:latest

RUN dnf5 install -y  \
    ansible \
    curl \
    isomd5sum \
    jq \
    parted \
    tree \
    xorriso && \
    curl -L 'https://raw.githubusercontent.com/ublue-os/isogenerator/main/isopatch.sh' -o /usr/local/bin/isopatch.sh && \
    chmod +x /usr/local/bin/isopatch.sh

ENTRYPOINT ["/usr/local/bin/isopatch.sh"]
