FROM fedora-minimal:38 as builder
ARG FLARECTL_VERSION=0.66.0
ARG FLARECTL_RELEASE=https://github.com/cloudflare/cloudflare-go/releases/download/v${FLARECTL_VERSION}/flarectl_${FLARECTL_VERSION}_linux_amd64.tar.xz

RUN dnf5 install -y tar xz && \
    curl -L "${FLARECTL_RELEASE}" --output /tmp/flarectl.tar.xz && \
    tar xvf /tmp/flarectl.tar.xz

FROM scratch

COPY --from=0 /flarectl /flarectl

ENTRYPOINT ["/flarectl"]
