FROM fedora:latest


COPY scripts/* /usr/local/bin
COPY systemd/container-launch.service /usr/lib/systemd/system
COPY systemd/override.conf /etc/systemd/system/console-getty.service.d/override.conf

RUN /usr/local/bin/prepare && systemctl enable container-launch

HEALTHCHECK CMD /usr/local/bin/health-check

ENTRYPOINT ["/sbin/init"]
