FROM ghcr.io/akdev1l/container-images/base:latest
ARG COSIGN_VERSION=2.0.1

RUN dnf5 install -y \
	"https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-${COSIGN_VERSION}.x86_64.rpm"

ENTRYPOINT ["cosign"]
