FROM ghcr.io/akdev1l/container-images/base:latest

RUN sed -i \
    -e '/\[main]/a\\keepcache=True' \
    -e '/\[main]/a\\install_weak_deps=False' \
    -e '/nodocs/d' /etc/dnf/dnf.conf

RUN dnf install -y \
    zsh \
    vim-enhanced \
    git \
    ripgrep \
    file \
    /usr/bin/ps \
    podman \
    buildah \
    skopeo \
    ansible \
    openssh-clients \
    make \
    'gcc-c++' \
    'gcc' \
    clang \
    cmake \
    java-latest-openjdk \
    nodejs \
    ;

RUN dnf swap -y \
    fedora-release-identity-container \
    fedora-release-identity-server \
    ;

RUN install -m 440 \
    /dev/stdin \
    /etc/sudoers.d/wheel-nopasswd <<<'%wheel ALL=(ALL) NOPASSWD: ALL'

COPY files/vim/vimrc /etc/vimrc.local
COPY util/ /tmp/util

RUN env \
    ZSH=/etc/oh-my-zsh \
    CHSH=no \
    RUNZSH=no \
    /tmp/util/install-oh-my-zsh.sh

RUN rm -rf /tmp/* /var/cache/* /var/log/*
