name: build customized container images

on:
  schedule:
    - cron: '30 4 * * 6'
  push:
    paths-ignore: '**.md'
    branches: [ "master" ]

jobs:
  publish:
    strategy:
      matrix:
        image:
          - awscdk
          - ghcli
          - iotop
          - jekyll
          - pandoc
          - ripgrep
          - watch_gha_runs
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io/${{ github.repository }}

    - name: publish all container images
      run: ./build.sh ${{ matrix.image }}
